apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  labels:
    app.kubernetes.io/name: app2
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/adrian-ramirezc/argocd-example-apps.git
    targetRevision: HEAD
    path: app-of-apps/app2
  destination:
    server: https://kubernetes.default.svc
    namespace: app2-ns