apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: app3-ns
  labels:
    app.kubernetes.io/name: app3
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/adrian-ramirezc/argocd-example-apps.git
    targetRevision: HEAD
    path: 'app'
    helm:
      valueFiles:
        - 'app3/values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: app3-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true