apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment-2
  labels:
    app: example-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app-2
  template:
    metadata:
      labels:
        app: example-app-2
    spec:
      containers:
        - name: example-container
          image: nginx:1.19.4
          ports:
            - containerPort: 80