apiVersion: batch/v1
kind: Job
metadata:
  name: check-rollout-status
  namespace: blue-green
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: check-rollout
          image: localhost/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get rollout example-deployment-rollout -n default -o jsonpath='{.status.phase}' | grep -q 'Healthy'; do
                echo "Waiting for rollout to complete..."
                sleep 5
              done
              echo "Rollout completed successfully."
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      restartPolicy: Never
  backoffLimit: 4