apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-status-checker
  namespace: blue-green
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-status-checker-sa
  namespace: blue-green