apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-deployment-rollout-2
  labels:
    app: example-app-2
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example-app-2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment-2
    scaleDown: onsuccess