apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: blue-green
  annotations:
    # By default, the sync wave is 0, we need to set it to 1 to ensure that this resource is sync at last.
    argocd.argoproj.io/sync-wave: "2"
  name: example-deployment-rollout-2
  labels:
    app: example-app-2
spec:
  replicas: 5
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: example-app-2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 2s}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment-2
    scaleDown: onsuccess