apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: blue-green
  name: rollout-1
  labels:
    app: deployment-1
spec:
  replicas: 10
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deployment-1
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 5s}
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name: should-fail
                templateName: non-existing-template
                clusterScope: false
                requiredForCompletion: true
                args:
                  - name: app-name
                    value: "deployment-1"
                  - name: canary
                    value: "some-value"
        - setWeight: 100
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-1
    scaleDown: onsuccess