apiVersion: batch/v1
kind: Job
metadata:
  name: check-rollout-status
  namespace: blue-green
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      serviceAccountName: rollouts-status-checker-sa
      containers:
        - name: check-rollout
          image: localhost/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get rollout example-deployment-rollout -n blue-green -o jsonpath='{.status.phase}' | grep -q 'Healthy'; do
                echo "Waiting for rollout to complete..."
                sleep 5
              done
              echo "Rollout completed successfully."
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-status-checker-binding
  namespace: blue-green
subjects:
  - kind: ServiceAccount
    name: rollout-status-checker-sa
    namespace: blue-green
roleRef:
  kind: Role
  name: rollout-status-checker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-status-checker
  namespace: blue-green
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-status-checker-sa
  namespace: blue-green