apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: app2-ns
  name: store-rollout
  labels:
    app: store-deployment
spec:
  replicas: 10
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: store-deployment
  strategy:
    canary:
      steps:
        - pause: { duration: 5s }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name: should-fail
                templateName: non-existing-template
                clusterScope: false
                requiredForCompletion: true
                args:
                  - name: app-name
                    value: "store-deployment"
                  - name: canary
                    value: "some-value"
        - pause: { duration: 2s }
        - setWeight: 100
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-deployment
    scaleDown: onsuccess