apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: status-checker-role-binding
  namespace: blue-green
subjects:
  - kind: ServiceAccount
    name: status-checker-sa
    namespace: blue-green
roleRef:
  kind: Role
  name: status-checker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: status-checker-role
  namespace: blue-green
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-checker-sa
  namespace: blue-green