apiVersion: batch/v1
kind: Job
metadata:
  name: status-checker-job
  namespace: app1-ns
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: status-checker-sa
      containers:
        - name: check-rollout
          image: localhost/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              all_healthy=false
              while [ "$all_healthy" = false ]; do
                status=$(kubectl get rollout store-rollout -n app1-ns -o jsonpath='{.status.phase}' 2>/dev/null)
                if [ "$status" = "Healthy" ]; then
                  all_healthy=true
                else
                  echo "Current rollout status: $status. Waiting for Healthy status..."
                  sleep 10
                fi
              done
              echo "Rollout completed successfully."
              exit 0
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: status-checker-role-binding
  namespace: app1-ns
subjects:
  - kind: ServiceAccount
    name: status-checker-sa
    namespace: app1-ns
roleRef:
  kind: Role
  name: status-checker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: status-checker-role
  namespace: app1-ns
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-checker-sa
  namespace: app1-ns